language: node_js

node_js:
  - "8"
  - "10"
  - "12"
  - "node"

sudo: false

cache:
    npm: false
    directories:
        - $HOME/.npm

install:
  - "npm install"

os:
  - "linux"
  - "osx"
  - "windows"
